#!/bin/bash
#
# TASK-001 probe builder — throwaway, like the probe itself.
#
# Assembles probes/task-001/build/Probe.app by hand and signs it as the LAST mutation of the
# bundle, because codesign seals Contents/ and anything written afterwards breaks the seal
# (findings §6, DEC-007).
#
# Flags exist only to produce the arms this card compares:
#   --tag X                   bakes a different constant into the source, so the binary and
#                             therefore the cdhash change; this is the "one-character source
#                             change" of question 1
#   --adhoc                   sign with `-` instead of the stable identity: the control arm
#   --no-usage-description    omit NSAppleEventsUsageDescription from Info.plist: question 2
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD="$HERE/build"
APP="$BUILD/Probe.app"
BUNDLE_ID="com.svvoff.terminator.probe"
IDENTITY="Terminator Dev"

TAG="A"
ADHOC=0
USAGE_DESCRIPTION=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag)                    TAG="$2"; shift 2 ;;
    --adhoc)                  ADHOC=1; shift ;;
    --no-usage-description)   USAGE_DESCRIPTION=0; shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

echo "--- building probe: tag=$TAG adhoc=$ADHOC usage-description=$USAGE_DESCRIPTION ---"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"

# The generated constant is the source change. Changing --tag changes the binary, which is
# what question 1 needs in order to ask whether the TCC grant survives it.
cat > "$BUILD/BuildTag.swift" <<EOF
// Generated by build-probe.sh. Not committed.
let buildTag = "$TAG"
EOF

echo "--- swiftc ---"
swiftc -o "$APP/Contents/MacOS/probe" \
    "$HERE/main.swift" "$BUILD/BuildTag.swift" \
    -framework AppKit

# Info.plist is written before signing and never touched after it.
USAGE_ENTRY=""
if [[ $USAGE_DESCRIPTION -eq 1 ]]; then
  USAGE_ENTRY='	<key>NSAppleEventsUsageDescription</key>
	<string>This throwaway probe measures how macOS handles Apple Events consent. It is not a product.</string>'
fi

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>probe</string>
	<key>CFBundleIdentifier</key>
	<string>$BUNDLE_ID</string>
	<key>CFBundleName</key>
	<string>Terminator TASK-001 Probe</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>13.0</string>
	<key>LSUIElement</key>
	<true/>
$USAGE_ENTRY
</dict>
</plist>
EOF

# ---- signing: the last mutation of the bundle ----
echo "--- codesign ---"
if [[ $ADHOC -eq 1 ]]; then
  codesign --force --sign - --identifier "$BUNDLE_ID" "$APP"
else
  codesign --force --sign "$IDENTITY" --identifier "$BUNDLE_ID" "$APP"
fi

echo "--- codesign --verify --strict (terminal step; its exit code is the verification) ---"
codesign --verify --strict --verbose=2 "$APP"

echo "--- codesign -dv ---"
codesign -dv "$APP" 2>&1

echo "--- codesign -d -r- (designated requirement) ---"
codesign -d -r- "$APP" 2>&1

echo "--- built: $APP ---"
